version: '3.7'
services:
    redis:
      image: redis:6.0.5
      command: redis-server --requirepass pass13 --port 6379
      container_name: redis
      hostname: redis
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
